(venv) root@ip-172-31-38-223:/www/wwwroot/hwosecurity.org# pip install mysqlclient
Collecting mysqlclient
  Using cached mysqlclient-2.2.7.tar.gz (91 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mysqlclient (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [249 lines of output]
      /tmp/pip-build-env-naydsd7e/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
      !!
      
              ********************************************************************************
              Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
      
              By 2026-Feb-18, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        corresp(dist, value, root_dir)
      /tmp/pip-build-env-naydsd7e/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        dist._finalize_license_expression()
      /tmp/pip-build-env-naydsd7e/overlay/lib/python3.10/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        self._finalize_license_expression()
      Trying pkg-config --exists mysqlclient
      # Options for building extension module:
        extra_compile_args: ['-I/usr/include/mysql', '-std=c99']
        extra_link_args: ['-lmysqlclient']
        define_macros: [('version_info', (2, 2, 7, 'final', 0)), ('__version__', '2.2.7')]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/release.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/cursors.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/converters.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/_exceptions.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/connections.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/times.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      copying src/MySQLdb/__init__.py -> build/lib.linux-x86_64-cpython-310/MySQLdb
      creating build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      copying src/MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      copying src/MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      copying src/MySQLdb/constants/CR.py -> build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      copying src/MySQLdb/constants/ER.py -> build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      copying src/MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      copying src/MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-cpython-310/MySQLdb/constants
      running egg_info
      writing src/mysqlclient.egg-info/PKG-INFO
      writing dependency_links to src/mysqlclient.egg-info/dependency_links.txt
      writing top-level names to src/mysqlclient.egg-info/top_level.txt
      reading manifest file 'src/mysqlclient.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'src/mysqlclient.egg-info/SOURCES.txt'
      copying src/MySQLdb/_mysql.c -> build/lib.linux-x86_64-cpython-310/MySQLdb
      running build_ext
      building 'MySQLdb._mysql' extension
      creating build/temp.linux-x86_64-cpython-310/src/MySQLdb
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC "-Dversion_info=(2, 2, 7, 'final', 0)" -D__version__=2.2.7 -I/www/wwwroot/hwosecurity.org/venv/include -I/usr/include/python3.10 -c src/MySQLdb/_mysql.c -o build/temp.linux-x86_64-cpython-310/src/MySQLdb/_mysql.o -I/usr/include/mysql -std=c99
      In file included from /usr/include/mysql/mysql.h:84,
                       from src/MySQLdb/_mysql.c:29:
      /usr/include/mysql/mysql/client_plugin.h:100:3: error: unknown type name ‘MYSQL’
        100 |   MYSQL *(*connect)(MYSQL *mysql, const char *host,
            |   ^~~~~
      /usr/include/mysql/mysql/client_plugin.h:100:21: error: unknown type name ‘MYSQL’
        100 |   MYSQL *(*connect)(MYSQL *mysql, const char *host,
            |                     ^~~~~
      /usr/include/mysql/mysql/client_plugin.h:104:17: error: unknown type name ‘MYSQL’
        104 |   void (*close)(MYSQL *mysql);
            |                 ^~~~~
      /usr/include/mysql/mysql/client_plugin.h:105:23: error: unknown type name ‘MYSQL’
        105 |   int (*set_optionsv)(MYSQL *mysql, unsigned int option, ...);
            |                       ^~~~~
      /usr/include/mysql/mysql/client_plugin.h:106:25: error: unknown type name ‘MYSQL’
        106 |   int (*set_connection)(MYSQL *mysql,enum enum_server_command command,
            |                         ^~~~~
      /usr/include/mysql/mysql/client_plugin.h:108:40: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        108 |                         size_t length, my_bool skipp_check, void *opt_arg);
            |                                        ^~~~~~~
            |                                        _Bool
      /usr/include/mysql/mysql/client_plugin.h:109:3: error: expected ‘;’ before ‘my_bool’
        109 |   my_bool (*reconnect)(MYSQL *mysql);
            |   ^~~~~~~
      In file included from /usr/include/mysql/mysql/client_plugin.h:116,
                       from /usr/include/mysql/mysql.h:84,
                       from src/MySQLdb/_mysql.c:29:
      /usr/include/mysql/ma_pvio.h:69:20: error: unknown type name ‘MYSQL’
         69 |   void (*callback)(MYSQL *mysql, uchar *buffer, size_t size);
            |                    ^~~~~
      /usr/include/mysql/ma_pvio.h:83:3: error: unknown type name ‘MYSQL’
         83 |   MYSQL *mysql;
            |   ^~~~~
      /usr/include/mysql/ma_pvio.h:85:21: error: unknown type name ‘MYSQL’
         85 |   void (*set_error)(MYSQL *mysql, unsigned int error_nr, const char *sqlstate, const char *format, ...);
            |                     ^~~~~
      /usr/include/mysql/ma_pvio.h:86:20: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
         86 |   void (*callback)(MARIADB_PVIO *pvio, my_bool is_read, const uchar *buffer, size_t length);
            |                    ^~~~~~~~~~~~
            |                    MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:86:40: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
         86 |   void (*callback)(MARIADB_PVIO *pvio, my_bool is_read, const uchar *buffer, size_t length);
            |                                        ^~~~~~~
            |                                        _Bool
      /usr/include/mysql/ma_pvio.h:97:3: error: unknown type name ‘MYSQL’
         97 |   MYSQL *mysql;
            |   ^~~~~
      /usr/include/mysql/ma_pvio.h:102:3: error: expected specifier-qualifier-list before ‘my_bool’
        102 |   my_bool (*set_timeout)(MARIADB_PVIO *pvio, enum enum_pvio_timeout type, int timeout);
            |   ^~~~~~~
      /usr/include/mysql/ma_pvio.h:122:1: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        122 | MARIADB_PVIO *ma_pvio_init(MA_PVIO_CINFO *cinfo);
            | ^~~~~~~~~~~~
            | MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:123:20: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        123 | void ma_pvio_close(MARIADB_PVIO *pvio);
            |                    ^~~~~~~~~~~~
            |                    MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:124:28: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        124 | ssize_t ma_pvio_cache_read(MARIADB_PVIO *pvio, uchar *buffer, size_t length);
            |                            ^~~~~~~~~~~~
            |                            MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:125:22: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        125 | ssize_t ma_pvio_read(MARIADB_PVIO *pvio, uchar *buffer, size_t length);
            |                      ^~~~~~~~~~~~
            |                      MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:126:23: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        126 | ssize_t ma_pvio_write(MARIADB_PVIO *pvio, const uchar *buffer, size_t length);
            |                       ^~~~~~~~~~~~
            |                       MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:127:25: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        127 | int ma_pvio_get_timeout(MARIADB_PVIO *pvio, enum enum_pvio_timeout type);
            |                         ^~~~~~~~~~~~
            |                         MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:128:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        128 | my_bool ma_pvio_set_timeout(MARIADB_PVIO *pvio, enum enum_pvio_timeout type, int timeout);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:128:29: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        128 | my_bool ma_pvio_set_timeout(MARIADB_PVIO *pvio, enum enum_pvio_timeout type, int timeout);
            |                             ^~~~~~~~~~~~
            |                             MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:129:23: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        129 | int ma_pvio_fast_send(MARIADB_PVIO *pvio);
            |                       ^~~~~~~~~~~~
            |                       MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:130:23: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        130 | int ma_pvio_keepalive(MARIADB_PVIO *pvio);
            |                       ^~~~~~~~~~~~
            |                       MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:131:30: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        131 | my_socket ma_pvio_get_socket(MARIADB_PVIO *pvio);
            |                              ^~~~~~~~~~~~
            |                              MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:132:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        132 | my_bool ma_pvio_is_blocking(MARIADB_PVIO *pvio);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:132:29: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        132 | my_bool ma_pvio_is_blocking(MARIADB_PVIO *pvio);
            |                             ^~~~~~~~~~~~
            |                             MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:133:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        133 | my_bool ma_pvio_blocking(MARIADB_PVIO *pvio, my_bool block, my_bool *previous_mode);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:133:26: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        133 | my_bool ma_pvio_blocking(MARIADB_PVIO *pvio, my_bool block, my_bool *previous_mode);
            |                          ^~~~~~~~~~~~
            |                          MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:133:46: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        133 | my_bool ma_pvio_blocking(MARIADB_PVIO *pvio, my_bool block, my_bool *previous_mode);
            |                                              ^~~~~~~
            |                                              _Bool
      /usr/include/mysql/ma_pvio.h:133:61: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        133 | my_bool ma_pvio_blocking(MARIADB_PVIO *pvio, my_bool block, my_bool *previous_mode);
            |                                                             ^~~~~~~
            |                                                             _Bool
      /usr/include/mysql/ma_pvio.h:134:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        134 | my_bool ma_pvio_is_blocking(MARIADB_PVIO *pvio);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:134:29: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        134 | my_bool ma_pvio_is_blocking(MARIADB_PVIO *pvio);
            |                             ^~~~~~~~~~~~
            |                             MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:135:32: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        135 | int ma_pvio_wait_io_or_timeout(MARIADB_PVIO *pvio, my_bool is_read, int timeout);
            |                                ^~~~~~~~~~~~
            |                                MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:135:52: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        135 | int ma_pvio_wait_io_or_timeout(MARIADB_PVIO *pvio, my_bool is_read, int timeout);
            |                                                    ^~~~~~~
            |                                                    _Bool
      /usr/include/mysql/ma_pvio.h:136:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        136 | my_bool ma_pvio_connect(MARIADB_PVIO *pvio, MA_PVIO_CINFO *cinfo);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:136:25: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        136 | my_bool ma_pvio_connect(MARIADB_PVIO *pvio, MA_PVIO_CINFO *cinfo);
            |                         ^~~~~~~~~~~~
            |                         MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:137:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        137 | my_bool ma_pvio_is_alive(MARIADB_PVIO *pvio);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:137:26: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        137 | my_bool ma_pvio_is_alive(MARIADB_PVIO *pvio);
            |                          ^~~~~~~~~~~~
            |                          MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:138:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        138 | my_bool ma_pvio_get_handle(MARIADB_PVIO *pvio, void *handle);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:138:28: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        138 | my_bool ma_pvio_get_handle(MARIADB_PVIO *pvio, void *handle);
            |                            ^~~~~~~~~~~~
            |                            MARIADB_TLS
      /usr/include/mysql/ma_pvio.h:139:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
        139 | my_bool ma_pvio_has_data(MARIADB_PVIO *pvio, ssize_t *length);
            | ^~~~~~~
            | _Bool
      /usr/include/mysql/ma_pvio.h:139:26: error: unknown type name ‘MARIADB_PVIO’; did you mean ‘MARIADB_TLS’?
        139 | my_bool ma_pvio_has_data(MARIADB_PVIO *pvio, ssize_t *length);
            |                          ^~~~~~~~~~~~
            |                          MARIADB_TLS
      In file included from /usr/include/mysql/mysql.h:84,
                       from src/MySQLdb/_mysql.c:29:
      /usr/include/mysql/mysql/client_plugin.h:139:10: fatal error: ma_compress.h: No such file or directory
        139 | #include <ma_compress.h>
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mysqlclient
Failed to build mysqlclient
ERROR: Could not build wheels for mysqlclient, which is required to install pyproject.toml-based projects
(venv) root@ip-172-31-38-223:/www/wwwroot/hwosecurity.org# pip install pymysql
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 KB 1.5 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
(venv) root@ip-172-31-38-223:/www/wwwroot/hwosecurity.org# nano .env
(venv) root@ip-172-31-38-223:/www/wwwroot/hwosecurity.org# echo "pymysql>=1.1.0" >> requirements.txt
(venv) root@ip-172-31-38-223:/www/wwwroot/hwosecurity.org# python initialize.py
Traceback (most recent call last):
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'streamlit'@'localhost'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/wwwroot/hwosecurity.org/initialize.py", line 17, in <module>
    from app import db
  File "/www/wwwroot/hwosecurity.org/app.py", line 60, in <module>
    db.create_all()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5925, in create_all
    bind._run_ddl_visitor(
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3248, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3238, in begin
    with self.connect() as conn:
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1698, "Access denied for user 'streamlit'@'localhost'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(venv) root@ip-172-31-38-223:/www/wwwroot/hwosecurity.org# python initialize.py
Traceback (most recent call last):
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'streamlit'@'localhost'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/wwwroot/hwosecurity.org/initialize.py", line 17, in <module>
    from app import db
  File "/www/wwwroot/hwosecurity.org/app.py", line 60, in <module>
    db.create_all()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5925, in create_all
    bind._run_ddl_visitor(
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3248, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3238, in begin
    with self.connect() as conn:
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    with util.safe_reraise():
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/www/wwwroot/hwosecurity.org/venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1698, "Access denied for user 'streamlit'@'localhost'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)